taxi_rides_ny:
  target: dev

  outputs:
    dev:
      type: bigquery
      method: service-account
      project: elt-pipeline-with-kestra
      dataset: dbt_kjauregui
      threads: 4
      keyfile: /usr/app/terraform/credentials/terraform_nytaxi.json
      location: us-central1