name: dbt CI

on:
  push:
    branches: [main]
    paths:
      - "dbt/**"
  pull_request:
    branches: [main]
    paths:
      - "dbt/**"

jobs:
  dbt-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dbt
        run: pip install dbt-bigquery

      - name: Install dbt packages
        run: dbt deps
        working-directory: ./dbt

      - name: Validate dbt project
        run: dbt parse
        working-directory: ./dbt
        